name: "Deploy Amplify"
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: "Git ref"
        required: true
      image_tag:
        description: "Image tag"
        required: true

jobs:
  deploy_amplify:
    name: Deploy Flutter App to AWS Amplify
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Install AWS Amplify CLI
        run: curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL 
         
      - name: Confirm Amplify installed and check version   
        run: amplify -v
      
      - name: Initialize/Configure AWS Amplify CLI
        run: bash ./.github/workflows/amplify_init.sh

      - name: Push Amplify project to AWS
        run: bash ./.github/worfklows/amplify_push.sh
        

      
